### ISSUE TITLE
Small races from mods like Origin's not resizing

### ISSUE THREAD

**Issue by DynamicMountain** [textstack/band_of_gigantism#11]
**Describe the bug**
Currently with this mod, if used with Origins, smaller races are unable to equip any gigantism ring, whereas any normal sized or bigger race are able to equip and utilize the rings

**To Reproduce**
Pick a small Race

**Expected behavior**
Make smaller race bigger or smaller
Equip ring / mask

**Versions (Important! Please do this):**
 - Minecraft version: 1.18.2
 - Forge version: 40.1.20
 - Mod version: 1.10

**Additional context**

**Comment by textstack** [comment]
I know EXACTLY why this occurs. TL;DR Band of Gigantism is keeping itself from breaking the player's scale.

Band of Gigantism, like Origins, uses Pehkui to rescale the player. Pehkui has a bunch of different scale types (movement, width, height, etc.) that are all stored to the player as a single value each. This is far more simple than, say, Minecraft's attribute system, which stores each modifier and adds them all together.

The reason this is important is because if multiple sources affect a particular scale, there's nothing keeping track of what modifies what or what order to apply the changes, as all that's stored is the final result. Therefore, if two different sources affect a single scale type, neither source is able to know that the other is also affecting the scale, and neither source has any set order of operations. This could be done separately of course, but it'd still be an issue with two sources across two mods.

Band of Gigantism avoids this altogether by simply preventing the curios from being equipped if the scales it affects are at all changed (it actually just checks width but that can be changed). This is especially important as Band of Gigantism simply sets the player's scale, rather than adding to it or multiplying it. This keeps the bands from scaling the player to an unexpected amount, but will almost certainly set the scale incorrectly if the player's scale isn't 1.

The reason that the bands work with bigger origins is simple: Origins uses different scale types. When making the player bigger, Origins probably uses the _base_ scale type, which Band of Gigantism never touches. However, because the base scale type affects jump height, Origins uses the _width_ and _height_ scale types when shrinking the player to avoid the player being unable to jump up blocks. Therefore, equipping not allowed. If it was, the player's smaller size would get completely overwritten.

This doesn't mean that it's impossible for smaller origins to use the band. This is a problem I've been thinking about since I've first started writing the mod, and I've considered ways around Pehkui's limits. It's just extremely difficult to find a way to scale the player when all you know is their scale.

For now, I guess treat smaller origins not being able to use bands as some kind of divine rejection or something.

**Comment by textstack** [comment]
Here's a beta build with an alternate scaling type.
In the config, enable `multiply_enable` under the general tab.
[band_of_gigantism-1.18.2-1.2.0b.zip](https://github.com/textstack/band_of_gigantism/files/8746922/band_of_gigantism-1.18.2-1.2.0b.zip)

**Comment by textstack** [comment]
The multiply_enable config has been released with 1.18.2-1.1.3. I haven't really touched it since then, but I also haven't seen any problems.
